[package]
name = "tcp-multiple-listener-silo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version="1.42.0", features=["full", "rt", "io-util", "net", "sync", "time"]}
tokio-tungstenite = "0.26.1"
tungstenite = "0.26.1"